# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-28 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学院')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='专业')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department', verbose_name='学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('m_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='帐号')),
                ('m_contact', models.CharField(default='无', max_length=20, verbose_name='联系方式')),
                ('m_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.Department', verbose_name='学院')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'permissions': (('is_manager', 'is a manager'),),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='教研室')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department', verbose_name='学院')),
            ],
            options={
                'verbose_name': '教研室',
                'verbose_name_plural': '教研室',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开放时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department', verbose_name='学院')),
            ],
            options={
                'verbose_name': '系统开放时间',
                'verbose_name_plural': '系统开放时间',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('value', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False, verbose_name='年级')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
        migrations.AddField(
            model_name='time',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Year', verbose_name='年级'),
        ),
    ]
